### ISSUE TITLE
How to get TDWI ?

### ISSUE THREAD

**Issue by jiansuo** [ajwdewit/WOFOST_crop_parameters#2]
Hello, I want to know how to calculate TDWI, is it the weight of seed?

**Comment by ajwdewit** [comment]
Dear Jiansuo.

Yes it it basically calculated as the seed weight times the number of seeds per hectare. However, you could also argue that it is a bit of a calibration parameter which can be used to adjust the rate of increase of LAI.

with best regards,

Allard
