### ISSUE TITLE
Problem with barley.YAML

### ISSUE THREAD

**Issue by pedroalencar1** [ajwdewit/WOFOST_crop_parameters#3]
Hi there, 

I was trying to load the crop file for barley using `crop.set_active_crop('barley', 'Spring_barley_301')` and kept getting errors (KeyError:, originated at line L219 from yaml_cropdataprovider.py).

I decided to use the local file and kept getting similar errors. It just happens that, if one deletes the `Metadata` key from the file that is located before the CropParameters and the `meta` from `Variaties` it all works nicely (from local directory)

I also checked and the only files with the metadata key are barley.yaml and seed_onion.yaml. I suggest removing this session from the files until the `MultiCropDataProvider` can handle them 😄. 

Also, seed_onion is not listed in `.print_crops_varieties()`, but when I removed the metadata it appears in there. Is the file valid, or is it not reliable?

Finally, one problem that took me a while to figure out is that, to load local files using `YAMLCropDataProvider(fpath="my/path/to/crop/files")` there shouldn't be a file called `crops.yaml` in the same folder. If this file is there the function gets a "Version" error.  Maybe this should be added to the [manual](https://pcse.readthedocs.io/en/stable/reference_guide.html?highlight=%20YAMLCropDataProvider(fpath#data-providers-for-crop-parameter-values) 😅 

Many thanks for the attention and great assistance

**Comment by ajwdewit** [comment]
Dear Pedro,

Thanks for notifying the problem with the meta data in Barley and Onion. I will implement a fix for it.

The crops.yaml file is there on purpose: it is used as an entry point in the repository to find the available crop types in the repository. This ensures that the YAMLCropDataProvider can be used for other parameter set as well (for example the [parameters for the LINGRA crop model](https://github.com/ajwdewit/lingra_crop_parameters)).

The updated YAMLCropDataProvider that uses the crops.yaml file is already in the develop branch of pcse, but I did not find the time to release it on PyPI. Can you give it at try:
`pip install https://github.com/ajwdewit/pcse/archive/refs/heads/develop.zip`

with best regards,

Allard

**Comment by ajwdewit** [comment]
I pushed PCSE 5.5.2 to PyPI which should solve the problems with the metadata.

with best regards,

Allard

**Comment by pedroalencar1** [comment]
Dear Allard, sorry for the late response. I was on holidays.
Many thanks for the fixing!

Kind regards,

Pedro
