### ISSUE TITLE
WoFost considers North Chad as an area of high growth potential for Sorghum_VanHeemst_1988

### ISSUE THREAD

**Issue by akouete-kpakpo** [ajwdewit/WOFOST_crop_parameters#5]
## Context
@ajwdewit, my students at AI Summer School in Benin produced this map for Chad

![image](https://user-images.githubusercontent.com/26568112/183780912-3009edb4-d7ea-4944-b51f-81b9e2a2745d.png)

The index we used for every commune is $$\int_{t} LAI $$.

The WoFost model seems to consider North Chad as an area of high growth potential for Sorghum_VanHeemst_1988. Whereas it is a desertic area. Cf plot on [Maps](https://www.google.fr/maps/place/8%C2%B024'58.9%22N+18%C2%B032'22.7%22E/@16.8479004,18.704973,2072586m/data=!3m1!1e3!4m5!3m4!1s0x0:0x598f0b63469d67ec!8m2!3d8.4163542!4d18.5396344)

![image](https://user-images.githubusercontent.com/26568112/183781406-277f7e52-74ea-476b-a135-51249f7ad34f.png)

This is counter intuitive but could be explained by this comment of my student Consolas Hodonou

>Yes, at first glance, it is surprising.

>Except that in Chad, in spite of this desert character, the producers have developed techniques of production of sorghum in off-season. They produce sorghum on clay soils with a high water retention capacity, which means that after transplanting the plants, even in the dry season or without continuous watering, the sorghum manages to develop. But these are one or two specific varieties of sorghum and these varieties have adapted to these conditions... I suppose that if we run the model on other varieties of sorghum, the result will be quite different. I do not know the edaphic factors of Chad, but if we assume that there is more land unsuitable for sorghum cultivation in the north, the development of this off-season technique will be more important there. The other zones of the country have therefore prioritized other crops or other varieties of sorghum, which are adapted to the conditions in these zones...

## Steps to reproduce
```python
yaml_agro_template = """
- 2006-01-01:
    CropCalendar:
        crop_name: sorghum
        variety_name: Sorghum_VanHeemst_1988
        crop_start_date: 2006-03-31
        crop_start_type: emergence
        crop_end_date: 2006-10-20
        crop_end_type: harvest
        max_duration: 300
    TimedEvents: null
    StateEvents: null
"""
```

**Comment by ajwdewit** [comment]
Hi, it depends on the production level. If you are running potential production, I can imagine that North-Chad is an area where high production levels are possible (high temperature, lots of radiation). However, the values that you are plotting are unclear to me. They go up to 160, what variable are you plotting in the map and what are the units?
