### ISSUE TITLE
Map of high growth potential areas for Rice in Benin is not consistent with high productivity areas 

### ISSUE THREAD

**Issue by akouete-kpakpo** [ajwdewit/WOFOST_crop_parameters#6]
## Context
@ajwdewit, my students at AI Summer School in Benin produced this map for Rice in Benin

![image](https://user-images.githubusercontent.com/26568112/183782508-112498f4-ffc3-4fcc-b5af-0aac9cc7d51e.png)

We were expecting something like 

![image](https://user-images.githubusercontent.com/26568112/183782777-39d5fc8d-2a1a-4f13-a95d-02e5af1374f3.png)

Could you help us understand the discrepancy?

**Comment by ajwdewit** [comment]
dear akouete-kpakpo,

What am I looking at? the first map: Is this potential production or water-limited production for rice in Benin? The second map: are these yield levels based on regional yield statistics?

Allard
