### ISSUE TITLE
WoFost model does not handle negative impact of too much irrigation

### ISSUE THREAD

**Issue by akouete-kpakpo** [ajwdewit/WOFOST_crop_parameters#7]
## Context

While computing the index 

$$
-\int_t LAI = loss (irrigation\ volume\ in\ cm)
$$

I noticed that too much irrigation does not have negative impact on the growth of Sugarbeet_603

![image](https://user-images.githubusercontent.com/26568112/183782993-695f6e07-5112-4231-9781-ffc0619fb2e4.png)

Is the feature not implemented yet in the WoFost model?

**Comment by ajwdewit** [comment]
dear Kpakpo Akouété,

sorry for the late reply. This was in my summer holiday and I did not notice your comments. Next time better email my on my WUR address.

Do your questions still require an answer or did you find the solutions yourself?

with best regards,

Allard

**Comment by akouete-kpakpo** [comment]
HI @ajwdewit 

no issue. Thanks for you reply. 

Yes I had your answer by mail

> I assume you are running the WOFOST model for water-limited production in the default settings. If so, oxygen limitations are not enabled so indeed, adding too much water will not lead to a decrease in crop yield because the model is not sensitive to it. You can enable oxygen stress by setting the parameter IOX=1. However, the amount of oxygen stress will also depend on the soil properties. If you have a deep well drained soil you may never see any oxygen stress. You can force oxygen stress by setting a low percolation rate, so for example setting parameter SOPE=0.1 which implies a percolation rate of maximal 1 mm/day.

> Moreover, in practice, putting a lot of water will lead to all kind of other problems related to plant disease, pests and/or erosion caused by surface runoff. The latter are not taken into account by WOFOST (and not by any crop model I know of).
